# Pymatgen
* Source Code: https://pymatgen.org/_modules/pymatgen/core/structure.html
* Docs: https://pymatgen.org/introduction.html


In [1]:
import pymatgen
from pymatgen import Lattice, Structure, Molecule

### Loading .cif file in parser to obtain Structure

In [2]:
from pymatgen.io.cif import CifParser
parser = CifParser("Si_mp-149_computed.cif")
structure = parser.get_structures()[0]

In [3]:
structure

Structure Summary
Lattice
    abc : 3.86697465 3.8669746499999995 3.8669746499999995
 angles : 60.00000000000001 60.00000000000001 60.00000000000001
 volume : 40.88829274510335
      A : 1.1162994275634794 3.1573715802591895 1.9334873250000004
      B : 1.1162994275634794 3.1573715802591895 -1.9334873249999995
      C : -2.2325988551269584 3.1573715802591895 -0.0
PeriodicSite: Si (0.0000, 7.1041, 0.0000) [0.7500, 0.7500, 0.7500]
PeriodicSite: Si (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]

### Covalent Radii

In [2]:
covalent_radii= '''
H 0.23 V 1.33 Rh 1.45 Ho 1.74 Ac 1.88
He 0.93 Cr 1.35 Pd 1.5 Er 1.73 Th 1.79
Li 0.68 Mn 1.35 Ag 1.59 Tm 1.72 Pa 1.61
Be 0.35 Fe 1.34 Cd 1.69 Yb 1.94 U 1.58
B 0.83 Co 1.33 In 1.63 Lu 1.72 Np 1.55
C 0.68 Ni 1.5 Sn 1.46 Hf 1.57 Pu 1.53
N 0.68 Cu 1.52 Sb 1.46 Ta 1.43 Am 1.51
O 0.68 Zn 1.45 Te 1.47 W 1.37 Cm 1.5
F 0.64 Ga 1.22 I 1.4 Re 1.35 Bk 1.5
Ne 1.12 Ge 1.17 Xe 1.98 Os 1.37 Cf 1.5
Na 0.97 As 1.21 Cs 1.67 Ir 1.32 Es 1.5
Mg 1.1 Se 1.22 Ba 1.34 Pt 1.5 Fm 1.5
Al 1.35 Br 1.21 La 1.87 Au 1.5 Md 1.5
Si 1.2 Kr 1.91 Ce 1.83 Hg 1.7 No 1.5
P 0.75 Rb 1.47 Pr 1.82 Tl 1.55 Lr 1.5
S 1.02 Sr 1.12 Nd 1.81 Pb 1.54 Rf 1.6
Cl 0.99 Y 1.78 Pm 1.8 Bi 1.54 Db 1.6
Ar 1.57 Zr 1.56 Sm 1.8 Po 1.68 Sg 1.6
K 1.33 Nb 1.48 Eu 1.99 At 1.7 Bh 1.6
Ca 0.99 Mo 1.47 Gd 1.79 Rn 2.4 Hs 1.6
Sc 1.44 Tc 1.35 Tb 1.76 Fr 2 Mt 1.6
Ti 1.47 Ru 1.4 Dy 1.75 Ra 1.9 
'''
covalent_radii=covalent_radii.split('\n')[1:-1]

In [3]:
covalent_dict={}

for line in covalent_radii:
    line=line.split()
    for i in range(0,len(line),2):
        covalent_dict[line[i]]=float(line[i+1])

covalent_dict

{'H': 0.23,
 'V': 1.33,
 'Rh': 1.45,
 'Ho': 1.74,
 'Ac': 1.88,
 'He': 0.93,
 'Cr': 1.35,
 'Pd': 1.5,
 'Er': 1.73,
 'Th': 1.79,
 'Li': 0.68,
 'Mn': 1.35,
 'Ag': 1.59,
 'Tm': 1.72,
 'Pa': 1.61,
 'Be': 0.35,
 'Fe': 1.34,
 'Cd': 1.69,
 'Yb': 1.94,
 'U': 1.58,
 'B': 0.83,
 'Co': 1.33,
 'In': 1.63,
 'Lu': 1.72,
 'Np': 1.55,
 'C': 0.68,
 'Ni': 1.5,
 'Sn': 1.46,
 'Hf': 1.57,
 'Pu': 1.53,
 'N': 0.68,
 'Cu': 1.52,
 'Sb': 1.46,
 'Ta': 1.43,
 'Am': 1.51,
 'O': 0.68,
 'Zn': 1.45,
 'Te': 1.47,
 'W': 1.37,
 'Cm': 1.5,
 'F': 0.64,
 'Ga': 1.22,
 'I': 1.4,
 'Re': 1.35,
 'Bk': 1.5,
 'Ne': 1.12,
 'Ge': 1.17,
 'Xe': 1.98,
 'Os': 1.37,
 'Cf': 1.5,
 'Na': 0.97,
 'As': 1.21,
 'Cs': 1.67,
 'Ir': 1.32,
 'Es': 1.5,
 'Mg': 1.1,
 'Se': 1.22,
 'Ba': 1.34,
 'Pt': 1.5,
 'Fm': 1.5,
 'Al': 1.35,
 'Br': 1.21,
 'La': 1.87,
 'Au': 1.5,
 'Md': 1.5,
 'Si': 1.2,
 'Kr': 1.91,
 'Ce': 1.83,
 'Hg': 1.7,
 'No': 1.5,
 'P': 0.75,
 'Rb': 1.47,
 'Pr': 1.82,
 'Tl': 1.55,
 'Lr': 1.5,
 'S': 1.02,
 'Sr': 1.12,
 'Nd': 1.81,
 'Pb': 1.54,
 

### Fetching API Key

In [4]:
with open('API.cfg') as f:
    print(f.read())

'DwTHn4JkLi01OXhu'


### Getting Structure and Properties using material-id

In [5]:
from pymatgen import MPRester
API_KEY='DwTHn4JkLi01OXhu'

with MPRester(API_KEY) as m:

    # Structure for material id
    structure = m.get_structure_by_material_id("mp-978259")
    
    # Dos for material id
    dos = m.get_dos_by_material_id("mp-1234")

    # Bandstructure for material id
    bandstructure = m.get_bandstructure_by_material_id("mp-1234")

In [6]:
structure

Structure Summary
Lattice
    abc : 8.879388953113947 8.879388953113947 4.586183
 angles : 90.0 90.0 152.49158300564798
 volume : 167.01123080329418
      A : 2.111139 -8.624769 0.0
      B : 2.111139 8.624769 0.0
      C : 0.0 0.0 4.586183
PeriodicSite: Mg (2.1111, -7.4946, 3.4396) [0.9345, 0.0655, 0.7500]
PeriodicSite: Mg (2.1111, -4.0875, 3.4396) [0.7370, 0.2630, 0.7500]
PeriodicSite: Mg (2.1111, 4.0875, 1.1465) [0.2630, 0.7370, 0.2500]
PeriodicSite: Mg (2.1111, 7.4946, 1.1465) [0.0655, 0.9345, 0.2500]
PeriodicSite: As (2.1111, 2.7993, 3.4396) [0.3377, 0.6623, 0.7500]
PeriodicSite: As (2.1111, -2.7993, 1.1465) [0.6623, 0.3377, 0.2500]

In [7]:
dos.as_dict().keys()

dict_keys(['@module', '@class', 'efermi', 'structure', 'energies', 'densities', 'pdos', 'atom_dos', 'spd_dos'])

In [8]:
bandstructure.as_dict().keys()

dict_keys(['@module', '@class', 'lattice_rec', 'efermi', 'kpoints', 'branches', 'bands', 'is_metal', 'vbm', 'cbm', 'band_gap', 'labels_dict', 'is_spin_polarized'])

## Structure Exploration

In [9]:
structure.formula

'Mg4 As2'

In [10]:
all_sites=structure.sites
all_sites

[PeriodicSite: Mg (2.1111, -7.4946, 3.4396) [0.9345, 0.0655, 0.7500],
 PeriodicSite: Mg (2.1111, -4.0875, 3.4396) [0.7370, 0.2630, 0.7500],
 PeriodicSite: Mg (2.1111, 4.0875, 1.1465) [0.2630, 0.7370, 0.2500],
 PeriodicSite: Mg (2.1111, 7.4946, 1.1465) [0.0655, 0.9345, 0.2500],
 PeriodicSite: As (2.1111, 2.7993, 3.4396) [0.3377, 0.6623, 0.7500],
 PeriodicSite: As (2.1111, -2.7993, 1.1465) [0.6623, 0.3377, 0.2500]]

In [11]:
structure.num_sites

6

### Fetching Unique Elements

In [12]:
unique_sites=set()
for site in all_sites:
    unique_sites.add(site.species_string)
unique_sites

{'As', 'Mg'}

In [13]:
# structure.symbol_set

### Calculating Sum of Covalent Radii 

In [14]:
covalent_sum=0
for site in unique_sites:
    print(site,covalent_dict.get(site))
    covalent_sum+=covalent_dict.get(site)
    
covalent_sum

As 1.21
Mg 1.1


2.31

### Distance Matrix

In [15]:
import numpy as np

distance_matrix=[]
for i in all_sites:
    current=[]
    for j in all_sites:
        current.append(i.distance(j))
    distance_matrix.append(current)

distance_matrix = np.reshape(distance_matrix,(len(all_sites),len(all_sites)))
print(distance_matrix)

[[0.         3.4071115  4.29665941 3.21980062 2.69126683 5.01552006]
 [3.4071115  0.         3.1491957  4.29665941 2.73449678 2.63018053]
 [4.29665941 3.1491957  0.         3.4071115  2.63018053 2.73449678]
 [3.21980062 4.29665941 3.4071115  0.         5.01552006 2.69126683]
 [2.69126683 2.73449678 2.63018053 5.01552006 0.         4.34433089]
 [5.01552006 2.63018053 2.73449678 2.69126683 4.34433089 0.        ]]


In [22]:
print(distance_matrix-2.7)

[[-2.7         0.7071115   1.59665941  0.51980062 -0.00873317  2.31552006]
 [ 0.7071115  -2.7         0.4491957   1.59665941  0.03449678 -0.06981947]
 [ 1.59665941  0.4491957  -2.7         0.7071115  -0.06981947  0.03449678]
 [ 0.51980062  1.59665941  0.7071115  -2.7         2.31552006 -0.00873317]
 [-0.00873317  0.03449678 -0.06981947  2.31552006 -2.7         1.64433089]
 [ 2.31552006 -0.06981947  0.03449678 -0.00873317  1.64433089 -2.7       ]]


In [29]:
((distance_matrix-2.7)<0).astype(int)

array([[1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1]])

In [34]:
((distance_matrix-2.7)<0).astype(int).sum()-6

8

In [16]:
# distance_matrix=structure.distance_matrix
# print(distance_matrix)

In [156]:
structure.DISTANCE_TOLERANCE

0.5

In [207]:
structure

Structure Summary
Lattice
    abc : 8.879388953113947 8.879388953113947 4.586183
 angles : 90.0 90.0 152.49158300564798
 volume : 167.01123080329418
      A : 2.111139 -8.624769 0.0
      B : 2.111139 8.624769 0.0
      C : 0.0 0.0 4.586183
PeriodicSite: Mg (2.1111, -7.4946, 3.4396) [0.9345, 0.0655, 0.7500]
PeriodicSite: Mg (2.1111, -4.0875, 3.4396) [0.7370, 0.2630, 0.7500]
PeriodicSite: Mg (2.1111, 4.0875, 1.1465) [0.2630, 0.7370, 0.2500]
PeriodicSite: Mg (2.1111, 7.4946, 1.1465) [0.0655, 0.9345, 0.2500]
PeriodicSite: As (2.1111, 2.7993, 3.4396) [0.3377, 0.6623, 0.7500]
PeriodicSite: As (2.1111, -2.7993, 1.1465) [0.6623, 0.3377, 0.2500]

In [186]:
structure.sites[0].coords

array([ 2.111139  , -7.49463102,  3.43963725])

In [187]:
structure.sites[0]

PeriodicSite: Mg (2.1111, -7.4946, 3.4396) [0.9345, 0.0655, 0.7500]

In [188]:
structure.sites[1]

PeriodicSite: Mg (2.1111, -4.0875, 3.4396) [0.7370, 0.2630, 0.7500]

In [189]:
structure.frac_coords

array([[0.934483, 0.065517, 0.75    ],
       [0.736964, 0.263036, 0.75    ],
       [0.263036, 0.736964, 0.25    ],
       [0.065517, 0.934483, 0.25    ],
       [0.337719, 0.662281, 0.75    ],
       [0.662281, 0.337719, 0.25    ]])

In [17]:
structure.make_supercell(2)

In [18]:
structure

Structure Summary
Lattice
    abc : 17.758777906227895 17.758777906227895 9.172366
 angles : 90.0 90.0 152.49158300564798
 volume : 1336.0898464263535
      A : 4.222278 -17.249538 0.0
      B : 4.222278 17.249538 0.0
      C : 0.0 0.0 9.172366
PeriodicSite: Mg (2.1111, -7.4946, 3.4396) [0.4672, 0.0328, 0.3750]
PeriodicSite: Mg (2.1111, -7.4946, 8.0258) [0.4672, 0.0328, 0.8750]
PeriodicSite: Mg (4.2223, 1.1301, 3.4396) [0.4672, 0.5328, 0.3750]
PeriodicSite: Mg (4.2223, 1.1301, 8.0258) [0.4672, 0.5328, 0.8750]
PeriodicSite: Mg (4.2223, -16.1194, 3.4396) [0.9672, 0.0328, 0.3750]
PeriodicSite: Mg (4.2223, -16.1194, 8.0258) [0.9672, 0.0328, 0.8750]
PeriodicSite: Mg (6.3334, -7.4946, 3.4396) [0.9672, 0.5328, 0.3750]
PeriodicSite: Mg (6.3334, -7.4946, 8.0258) [0.9672, 0.5328, 0.8750]
PeriodicSite: Mg (2.1111, -4.0875, 3.4396) [0.3685, 0.1315, 0.3750]
PeriodicSite: Mg (2.1111, -4.0875, 8.0258) [0.3685, 0.1315, 0.8750]
PeriodicSite: Mg (4.2223, 4.5372, 3.4396) [0.3685, 0.6315, 0.3750]
Periodic

In [31]:
len(structure.sites)

48

In [ ]:
structure.